### ISSUE TITLE
[Campus_network] Question: 断网主要现象

### ISSUE THREAD

**Issue by YDX-2147483647** [KJH-x/Batch_Collections#1]
请问断网主要现象是账号退出，还是登录了但无互联网？

现在用`ping`检测断网，主要是后者吗？

https://github.com/KJH-x/Batch_Collections/blob/e155ebc013ea77c2ebbc9e8d7ed4db70f87d90d2/Campus_network/Network_Alive.py#L129

## 场景

我有一个 POSIX 设备要保持在线，现在只检测了账号状态，不知是否可靠。

```bash
#!/bin/bash

status=`bitsrun status --json | jq '.error' --raw-output`

if [[ $status != 'ok' ]]; then
  echo "Status: $status. Relogin…"
  bitsrun logout
  bitsrun login
fi
```

**Comment by KJH-x** [comment]
利用ping是将两种情况都合并考虑了

前者和后者的直接结果都是上不了网，通过ping能较快的判断是否能建立连接，因此在脚本中使用了ping来检测。

这样能保证未登录、被意外下线、在线但莫名其妙断网三种情况都能积极的尝试重登（我只遇到了这三种，所以写的时候也只考虑了这三种，如有其他情况可以开多个issue描述）

当然，通用的方法会造成成因不详细的问题，即不知道到底是为什么没网，后续可能考虑多种判断方法结合来跟踪记录断网情形

**Comment by YDX-2147483647** [comment]
明白了，谢谢回答。
